table FactInternetSales
	lineageTag: 2f6f3292-07f5-4ac1-8892-6da517aa3481
	sourceLineageTag: [dbo].[FactInternetSales]

	measure 'Sales Amount' =
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * FactInternetSales[UnitPrice]
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 3d66b4ba-e9f3-4f69-8d97-2671fe65507a

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ProductKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c1e72002-85c2-4c4a-851f-e51b6c093984
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1ea72ad2-900e-4a3a-9b68-4c79ed956a8e
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 45a317eb-add8-4522-9e84-f9dd9aed902e
		sourceLineageTag: DueDateKey
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column ShipDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 51f195de-1599-4263-bf5f-cc47117b262a
		sourceLineageTag: ShipDateKey
		summarizeBy: none
		sourceColumn: ShipDateKey

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 37e89242-e5c5-4cbe-b4e9-dfff837f63b7
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fa4bb530-abb1-482e-a463-386d80bd3c1b
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: aacfc532-e639-4017-ac11-58b21bde69a1
		sourceLineageTag: OrderQuantity
		summarizeBy: none
		sourceColumn: OrderQuantity

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

	column UnitPrice
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: e9cbe718-b927-4425-a715-77f04117a24d
		sourceLineageTag: UnitPrice
		summarizeBy: none
		sourceColumn: UnitPrice

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		sourceProviderType: float
		lineageTag: 41d08090-7f9d-4e04-b701-b181a7652896
		sourceLineageTag: UnitPriceDiscountPct
		summarizeBy: none
		sourceColumn: UnitPriceDiscountPct

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: b1f142ed-f498-46ef-ac1b-0e00b12de14b
		sourceLineageTag: ProductStandardCost
		summarizeBy: none
		sourceColumn: ProductStandardCost

		changedProperty = SummarizeBy

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = entity
		mode: directLake
		source
			entityName: FactInternetSales
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

