table FactInternetSales
	lineageTag: 21b3c8bc-87b2-4848-918a-43f6d958f9ab
	sourceLineageTag: [dbo].[FactInternetSales]

	measure 'Sales Amount' = ```
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * 'FactInternetSales'[UnitPrice]
			)
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 17f1488e-3821-43c0-80bd-44a045155b64

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 253c9372-9255-4db2-b098-918521787493
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 73d78fca-e3b6-48ac-855d-20336bd3b995
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 1ebe6dda-b47c-4ec3-9ace-286399883d0d
		sourceLineageTag: DueDateKey
		summarizeBy: none
		sourceColumn: DueDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 93d0a67f-0394-466e-ba3a-946b960cae05
		sourceLineageTag: ShipDateKey
		summarizeBy: none
		sourceColumn: ShipDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: b2a76e9a-b7bf-4830-8cb7-2afa4cece05a
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5a1f4dfb-90ba-42e7-8aeb-04823dd4c215
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: dadff2c0-8e38-4fcb-b826-bef6f1c953b6
		sourceLineageTag: OrderQuantity
		summarizeBy: none
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 5e9a97b5-e9ab-41d3-b44d-d9baf29c1e51
		sourceLineageTag: UnitPrice
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		sourceProviderType: float
		lineageTag: a2caaf0b-6aeb-4de2-9443-4071806aa3b3
		sourceLineageTag: UnitPriceDiscountPct
		summarizeBy: none
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 64cff88d-148e-45fe-8140-dd18a719dbb7
		sourceLineageTag: ProductStandardCost
		summarizeBy: none
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = entity
		mode: directLake
		source
			entityName: FactInternetSales
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

