table FactInternetSales
	lineageTag: eca5098b-b28f-42da-bca1-1411691a5422

	measure 'Sales Amount' =
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * 'FactInternetSales'[UnitPrice]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Measures
		lineageTag: 41ab48d8-bc19-47f9-9ec9-bc3027ca214c

	measure Customers = ```
			DISTINCTCOUNT('FactInternetSales'[CustomerKey]) 
			```
		formatString: #,0
		displayFolder: Measures
		lineageTag: 7337113e-2420-4c31-8467-d0ec50a66edf

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 90a13ad6-0fc0-4288-8353-9ae7f80b95e7
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		displayFolder: DatesKeys
		lineageTag: 497f9aeb-fe5a-40e1-91fc-cb3713ccd8c0
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		displayFolder: DatesKeys
		lineageTag: bae195af-1bd4-49d4-9d9e-7ce4eae705c8
		summarizeBy: none
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = User

	column ShipDateKey
		dataType: int64
		formatString: 0
		displayFolder: DatesKeys
		lineageTag: 2d47e344-263d-4ae8-a77c-53ae5b080965
		summarizeBy: none
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = User

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: c79d310d-0a3e-43c9-856a-a5cec4123214
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		displayFolder: NumericCols
		lineageTag: 7659d1f8-6085-4346-a4a3-c0a075ddf7ae
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		displayFolder: NumericCols
		lineageTag: 446a5347-c466-4cbe-8c53-50c526677541
		summarizeBy: none
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = User

	column UnitPrice
		dataType: double
		displayFolder: NumericCols
		lineageTag: 15d0ddce-916a-43a0-9951-fdc8aeed658f
		summarizeBy: none
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		displayFolder: NumericCols
		lineageTag: cd322bb2-daca-4aca-b1e0-67f32f2fa99f
		summarizeBy: none
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		displayFolder: NumericCols
		lineageTag: 7fd71a70-af59-472f-836e-638deaa0b087
		summarizeBy: none
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = m
		mode: import
		source =
				let
				    Source = Sql.Database(Server, Database),
				    dbo_FactInternetSales = Source{[Schema="dbo",Item="FactInternetSales"]}[Data]
				in
				    dbo_FactInternetSales

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

